version: '3.8'

services:
  server:
    image: miniserver:latets
    networks:
      - server-network

  nginx-proxy:
    image: nginx:latest
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:8080"
    depends_on:
      - server
    networks:
      - server-network

networks:
  server-network:
    driver: bridge
